from abc import ABC, abstractmethod
from typing import Optional
from app.core.config import get_settings
from app.core.logging import logger

settings = get_settings()

class ImageProvider(ABC):
    @abstractmethod
    async def generate_image(self, prompt: str) -> str:
        pass

class GeminiImageProvider(ImageProvider):
    async def generate_image(self, prompt: str) -> str:
        """
        Generates an image using Gemini Imagen 3 via the new google-genai SDK.
        """
        from google import genai
        from google.genai import types
        import os
        from PIL import Image
        import uuid
        from pathlib import Path
        import io
        
        logger.info(f"Generating image with Gemini Imagen for prompt: {prompt[:50]}...")
        
        try:
            # Use specific Imagen key if provided, otherwise fallback to default GEMINI_API_KEY
            api_key = settings.GEMINI_MODEL_IMAGEN_KEY or settings.GEMINI_API_KEY
            if not api_key:
                logger.error("No API key provided for Gemini Imagen")
                return "https://placehold.co/1024x1024/ef4444/white?text=No+API+Key"
                
            client = genai.Client(api_key=api_key)
            
            # Check if we should use generate_content (Gemini models) or generate_images (Imagen models)
            if "gemini" in settings.IMAGEN_MODEL_NAME.lower():
                logger.info(f"Using generate_content for model: {settings.IMAGEN_MODEL_NAME}")
                response = client.models.generate_content(
                    model=settings.IMAGEN_MODEL_NAME,
                    contents=prompt
                )
                
                # Extract image data from parts
                image_data = None
                for part in response.candidates[0].content.parts:
                    if part.inline_data:
                        image_data = part.inline_data.data
                        break
                
                if not image_data:
                    logger.error("No image data found in Gemini response parts")
                    return "https://placehold.co/1024x1024/ef4444/white?text=No+Image+in+Response"
            else:
                # Using Imagen 3/4
                logger.info(f"Using generate_images for model: {settings.IMAGEN_MODEL_NAME}")
                response = client.models.generate_images(
                    model=settings.IMAGEN_MODEL_NAME,
                    prompt=prompt,
                    config=types.GenerateImagesConfig(
                        number_of_images=1,
                    )
                )
                
                if not response.generated_images:
                    logger.error("No image generated by Gemini")
                    return "https://placehold.co/1024x1024/ef4444/white?text=Generation+Failed"
                
                image_data = response.generated_images[0].image
            # Create static directory if it doesn't exist
            try:
                static_dir = Path("static/generated_images")
                static_dir.mkdir(parents=True, exist_ok=True)
                
                filename = f"{uuid.uuid4()}.png"
                file_path = static_dir / filename
                
                # image_data can be bytes or a PIL Image depending on the SDK behavior
                if isinstance(image_data, bytes):
                    img = Image.open(io.BytesIO(image_data))
                    img.save(file_path)
                else:
                    # Assume it's a PIL Image
                    image_data.save(file_path)
                
                logger.info(f"Image saved to {file_path}")
                
                # Use localhost in development, otherwise use BACKEND_URL
                base_url = "http://localhost:8000" if settings.ENVIRONMENT == "development" else settings.BACKEND_URL
                return f"{base_url}/static/generated_images/{filename}"
            except (OSError, IOError) as e:
                logger.warning(f"Could not save image locally (read-only filesystem?): {e}")
                # For Gemini, if we can't save locally, we might not have a public URL to return
                # unless we upload it somewhere else. For now, we return a placeholder or error.
                return "https://placehold.co/1024x1024/3b82f6/white?text=Local+Save+Failed"
            
        except Exception as e:
            logger.error(f"Error in GeminiImageProvider: {e}")
            import urllib.parse
            encoded_prompt = urllib.parse.quote(prompt[:50] + "...")
            return f"https://placehold.co/1024x1024/ef4444/white?text=Error:+{encoded_prompt}"

class OpenAIImageProvider(ImageProvider):
    async def generate_image(self, prompt: str) -> str:
        from openai import AsyncOpenAI
        import uuid
        from pathlib import Path
        import httpx
        
        logger.info(f"Generating image with OpenAI for prompt: {prompt[:50]}...")
        
        try:
            client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)
            
            response = await client.images.generate(
                model=settings.OPENAI_IMAGE_MODEL_NAME,
                prompt=prompt,
                n=1,
                size="1024x1024",
                response_format="url"
            )
            
            image_url = response.data[0].url
            if not image_url:
                logger.error("No image URL returned from OpenAI")
                return "https://placehold.co/1024x1024/ef4444/white?text=Generation+Failed"

            # Download and save the image locally
            try:
                static_dir = Path("static/generated_images")
                static_dir.mkdir(parents=True, exist_ok=True)
                
                filename = f"{uuid.uuid4()}.png"
                file_path = static_dir / filename
                
                async with httpx.AsyncClient() as http_client:
                    image_response = await http_client.get(image_url)
                    if image_response.status_code == 200:
                        with open(file_path, "wb") as f:
                            f.write(image_response.content)
                        logger.info(f"Image saved to {file_path}")
                        
                        # Use localhost in development, otherwise use BACKEND_URL
                        base_url = "http://localhost:8000" if settings.ENVIRONMENT == "development" else settings.BACKEND_URL
                        return f"{base_url}/static/generated_images/{filename}"
                    else:
                        logger.error(f"Failed to download image from OpenAI: {image_response.status_code}")
                        return image_url # Return original URL as fallback
            except (OSError, IOError) as e:
                logger.warning(f"Could not save image locally (read-only filesystem?): {e}")
                return image_url # Return original OpenAI URL as fallback
            
        except Exception as e:
            logger.error(f"Error in OpenAIImageProvider: {e}")
            import urllib.parse
            encoded_prompt = urllib.parse.quote(prompt[:50] + "...")
            return f"https://placehold.co/1024x1024/ef4444/white?text=Error:+{encoded_prompt}"

class MockImageProvider(ImageProvider):
    async def generate_image(self, prompt: str) -> str:
        logger.info(f"Generating mock image for prompt: {prompt[:50]}...")
        return "https://via.placeholder.com/1024x1024.png?text=AI+Generated+Image"

class ImageService:
    def __init__(self, provider: ImageProvider):
        self.provider = provider

    async def generate_single_image(self, prompt: str) -> str:
        return await self.provider.generate_image(prompt)

def get_image_service() -> ImageService:
    # Logic to switch providers based on settings
    provider_type = getattr(settings, "IMAGE_PROVIDER", "openai").lower()
    
    if provider_type == "openai":
        provider = OpenAIImageProvider()
    elif provider_type == "gemini":
        provider = GeminiImageProvider()
    else:
        provider = MockImageProvider()
        
    return ImageService(provider)
