from abc import ABC, abstractmethod
from typing import Optional
from app.core.config import get_settings
from app.core.logging import logger

settings = get_settings()

class ImageProvider(ABC):
    @abstractmethod
    async def generate_image(self, prompt: str) -> str:
        pass

class GeminiImageProvider(ImageProvider):
    async def generate_image(self, prompt: str) -> str:
        """
        Generates an image using Gemini Imagen 3 via the new google-genai SDK.
        """
        from google import genai
        from google.genai import types
        import os
        from PIL import Image
        import uuid
        from pathlib import Path
        import io
        
        logger.info(f"Generating image with Gemini Imagen for prompt: {prompt[:50]}...")
        
        try:
            client = genai.Client(api_key=settings.GEMINI_API_KEY)
            
            # Using Imagen 3
            response = client.models.generate_images(
                model=settings.IMAGEN_MODEL_NAME,
                prompt=prompt,
                config=types.GenerateImagesConfig(
                    number_of_images=1,
                )
            )
            
            if not response.generated_images:
                logger.error("No image generated by Gemini")
                return "https://placehold.co/1024x1024/ef4444/white?text=Generation+Failed"

            # Create static directory if it doesn't exist
            static_dir = Path("static/generated_images")
            static_dir.mkdir(parents=True, exist_ok=True)
            
            filename = f"{uuid.uuid4()}.png"
            file_path = static_dir / filename
            
            # The new SDK returns image data in the response
            image_data = response.generated_images[0].image
            # image_data can be bytes or a PIL Image depending on the SDK behavior
            # According to docs, it's often a PIL Image or bytes.
            # Let's handle both.
            if isinstance(image_data, bytes):
                img = Image.open(io.BytesIO(image_data))
                img.save(file_path)
            else:
                # Assume it's a PIL Image
                image_data.save(file_path)
            
            logger.info(f"Image saved to {file_path}")
            
            # Return the URL. Assuming the app mounts /static
            return f"{settings.BACKEND_URL}/static/generated_images/{filename}"
            
        except Exception as e:
            logger.error(f"Error in GeminiImageProvider: {e}")
            import urllib.parse
            encoded_prompt = urllib.parse.quote(prompt[:50] + "...")
            return f"https://placehold.co/1024x1024/ef4444/white?text=Error:+{encoded_prompt}"

class MockImageProvider(ImageProvider):
    async def generate_image(self, prompt: str) -> str:
        logger.info(f"Generating mock image for prompt: {prompt[:50]}...")
        return "https://via.placeholder.com/1024x1024.png?text=AI+Generated+Image"

class ImageService:
    def __init__(self, provider: ImageProvider):
        self.provider = provider

    async def generate_single_image(self, prompt: str) -> str:
        return await self.provider.generate_image(prompt)

def get_image_service() -> ImageService:
    # Logic to switch providers based on settings
    provider_type = getattr(settings, "IMAGE_PROVIDER", "gemini").lower()
    
    if provider_type == "gemini":
        provider = GeminiImageProvider()
    else:
        provider = MockImageProvider()
        
    return ImageService(provider)
